#!/bin/bash

StartTime=$(date +%s)   # +%s 는 date의 포맷을 지정해주는 옵션이다.

# run something...
g++ -O2 -std=c++17 /Users/seonung/Documents/dev/alg/BOJ/solving/1202.cpp -o build/1202

EndTime=$(date +%s)

echo "It takes $(($EndTime - $StartTime)) seconds to complete this task."